### PR TITLE
feat: import and play m4a

### PR DESCRIPTION
**Pull request by daiyam**
This PR imports and plays M4A audio file.

M4A are quite tricky since we need to read the first buffer to get the channels configuration.

References:
- https://github.com/pdeljanov/Symphonia/issues/291

### CODE REVIEW

**Comment by daiyam** [comment]
It doesn't play the next song, yet...

**Comment by daiyam** [comment]
The tags are missing.

**Comment by daiyam** [comment]
The tags can't be written but I also have the issue with MP3 so that issue is outside the current PR.

**Comment by basharovV** [comment]
Thanks! I'll merge this, but note that there's an issue in Symphonia which causes some m4a files to fail to read with `Mp4: No "moov" atom found` error, see https://github.com/pdeljanov/Symphonia/issues/289. The same files work fine in other apps.

**Comment by daiyam** [comment]
So far, no issue with my m4a files.

**Pull request merged**
